FIO-7338: Fixes server crush when form id is 'undefined'
formio/formio pull request #1633
Opened 2023-09-19 13:12 UTC by mikekotikov

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-7338

## Description

**What changed?**

Previously, passing an `undefined` form id could sometimes crash the server. Now there's a check for form id, submission id and role id not to be equal to `undefined` or `null` strings. In case of being equal, an error would be returned from the API.

**Why have you chosen this solution?**

`params` middleware seemed to be a good place to make the check, since it's triggered nearly at the beginning and parses not only form id, but also submission id and role id from request params. 

## Dependencies

None

## How has this PR been tested?

I've added automated tests

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2023-09-21 22:22 UTC, brendanbond approved these changes

2023-09-21 22:30 UTC, brendanbond requested changes

2023-09-21 22:30 UTC, brendanbond commented on test/roles.js
> +          .get(hook.alter('url', '/role/undefined'))
this test fails when run versus formio-enterprise (the hook tries to read from `undefined`)

2023-09-26 07:06 UTC, mikekotikov commented
Will revisit to find a way to catch an error from db query in a proper way

2023-10-03 17:10 UTC, mikekotikov commented
This will be fixed in another PR, closing

2023-10-03 17:10 UTC, closed without merging