FIO-8295: cache promisifying, mongoose upgrade
formio/formio pull request #1766
Opened 2024-07-02 11:44 UTC by Maria-Golomb

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-8295
## Description
Cache was promisified
Mongoose version updated from 6.x to 8.x.
Mongodb version updated from 4.x to 6.x.
The code is refactored in accordance with updated dependencies requirements.
Failed tests are fixed.

## Dependencies
https://github.com/travist/resourcejs/pull/148

## How has this PR been tested?

Changes were checked with automated tests on local deployment using required dependencies (resoursejs)

## Checklist:

- [ x] I have completed the above PR template
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ x] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x ] New and existing unit/integration tests pass locally with my changes
- [x ] Any dependent changes have corresponding PRs that are listed above

2024-07-05 09:51 UTC, brendanbond requested changes
1. Merge conflicts
2. We definitely need tests passing here

2024-07-05 11:36 UTC, Maria-Golomb commented
Done.
Now tests fail because of using previous version of resoursejs.

2024-07-10 14:28 UTC, brendanbond requested changes
I've updated the resourcejs dependency to reflect your changes and the tests are still failing

2024-08-24 14:47 UTC, brendanbond approved these changes

2024-08-24 14:47 UTC, merged